[package]
name = "zero-ui-wgt-size_offset"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }

euclid = "0.22"
serde = { version = "1", features = ["derive"] }