[package]
name = "zng-ext-l10n"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-ext-l10n-proc-macros = { path = "../zng-ext-l10n-proc-macros" }

zng-app_context = { path = "../zng-app_context" }
zng-app = { path = "../zng-app" }
zng-var = { path = "../zng-var" }
zng-txt = { path = "../zng-txt" }
zng-clone_move = { path = "../zng-clone_move" }
zng-view-api = { path = "../zng-view-api" }
zng-layout = { path = "../zng-layout" }
zng-task = { path = "../zng-task" }
zng-ext-fs_watcher = { path = "../zng-ext-fs_watcher" }

fluent = "0.16"
fluent-syntax = "0.11"
intl-memoizer = "0.5"
parking_lot = "0.12"
unic-langid = "0.9"
tracing = "0.1"
unicase = "2"
once_cell = "1"