[package]
name = "zero-ui-ext-input"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zero-ui-app/README.md"

[dependencies]
zero-ui-app_context = { path = "../zero-ui-app_context" }
zero-ui-clone_move = { path = "../zero-ui-clone_move" }
zero-ui-view-api = { path = "../zero-ui-view-api" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-txt = { path = "../zero-ui-txt" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-layout = { path = "../zero-ui-layout" }
zero-ui-handle = { path = "../zero-ui-handle" }
zero-ui-state_map = { path = "../zero-ui-state_map" }
zero-ui-unique_id = { path = "../zero-ui-unique_id" }
zero-ui-ext-window = { path = "../zero-ui-ext-window" }

tracing = "0.1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
bitflags = "2"
atomic = "0.6"