[package]
name = "zng-wgt-toggle"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-button = { path = "../zng-wgt-button" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-layer = { path = "../zng-wgt-layer" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-scroll = { path = "../zng-wgt-scroll" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-filter = { path = "../zng-wgt-filter" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset" }
zng-wgt-style = { path = "../zng-wgt-style" }
zng-wgt-transform = { path = "../zng-wgt-transform" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-font = { path = "../zng-ext-font" }
zng-ext-l10n = { path = "../zng-ext-l10n" }
zng-var = { path = "../zng-var" }

parking_lot = "0.12"
tracing = "0.1"
