[package]
name = "zng-ext-config"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
yaml = ["dep:serde_yaml", "zng-ext-fs_watcher/yaml"]
toml = ["dep:toml", "zng-ext-fs_watcher/toml"]
ron = ["dep:ron", "zng-ext-fs_watcher/ron"]

[dependencies]
zng-app_context = { path = "../zng-app_context" }
zng-app = { path = "../zng-app" }
zng-var = { path = "../zng-var" }
zng-txt = { path = "../zng-txt" }
zng-task = { path = "../zng-task" }
zng-clone_move = { path = "../zng-clone_move" }
zng-unique_id = { path = "../zng-unique_id" }
zng-ext-fs_watcher = { path = "../zng-ext-fs_watcher", features = [
    "json",
] }

tracing = "0.1"
bytemuck = "1"
indexmap = { version = "2", features = ["serde"] }
atomic = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = { version = "0.8", optional = true, features = ["preserve_order"] }
ron = { version = "0.8", optional = true, features = ["indexmap"] }
serde_yaml = { version = "0.9", optional = true }
