[package]
name = "zng-wgt-access"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-app = { path = "../zng-app" }
zng-view-api = { path = "../zng-view-api" }
zng-wgt = { path = "../zng-wgt" }
zng-ext-l10n = { path = "../zng-ext-l10n" }