[package]
name = "zero-ui-docs"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[build-dependencies]
minifier = "0.0.43"