[package]
name = "zero-ui-derive"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.5", features = ["full", "visit-mut", "extra-traits"] }
quote = "1.0.2"