[package]
name = "zng-wgt-markdown"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-markdown"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-scroll = { path = "../zng-wgt-scroll" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-button = { path = "../zng-wgt-button" }
zng-wgt-stack = { path = "../zng-wgt-stack" }
zng-wgt-wrap = { path = "../zng-wgt-wrap" }
zng-wgt-rule-line = { path = "../zng-wgt-rule-line" }
zng-wgt-grid = { path = "../zng-wgt-grid" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-ansi-text = { path = "../zng-wgt-ansi-text" }
zng-wgt-layer = { path = "../zng-wgt-layer" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset" }
zng-wgt-transform = { path = "../zng-wgt-transform" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-image = { path = "../zng-wgt-image" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-filter = { path = "../zng-wgt-filter" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-image = { path = "../zng-ext-image" }
zng-ext-font = { path = "../zng-ext-font" }
zng-app = { path = "../zng-app" }

pulldown-cmark = "0.9"
http = "1"
path-absolutize = "3"
html-escape = "0.2"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
