[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[features]
app_profiler = ["serde_json", "lazy_static"]

[dependencies]
# local
zero-ui-macros = { path = "zero-ui-macros" }

# core
raw-window-handle = "0.3.3"
winapi = "0.3.9"
glutin = "0.25.1"
gleam = "0.6.17" #version required by webrender
webrender = "0.61.0"
euclid = "0.20.7" #version required by webrender
font-kit = "0.10.0"
harfbuzz_rs = "1.2.0"
xi-unicode = "0.2.1"
unicode-script = "0.5.2"
rayon = "1.4.1"
image = "0.23.10"

# util
once_cell = "1.4.1"
fnv = "1.0.7"
ego-tree = "0.6.2"
colored = "2.0.0"
derive_more = "0.99.11"
bitflags = "1.2.1"

# app_profiler only
serde_json = { version = "1.0", optional = true }
lazy_static = { version = "1", optional = true }

[dev-dependencies]
bencher = "0.1.5"
enclose = "1.1.8"

[workspace]
members = ["zero-ui-proc-macros", "zero-ui-macros"]

#[[bench]]
#name = "value_changed"
#harness = false