[workspace]

resolver = "2"

members = [
    # foundation:
    "zng-unique_id",
    "zng-clone_move",
    "zng-handle",
    "zng-txt",
    "zng-unit",
    "zng-state_map",
    "zng-app_context",
    "zng-layout",
    "zng-var-proc-macros",
    "zng-var",
    "zng-task-proc-macros",
    "zng-task",
    "zng-color-proc-macros",
    "zng-color",
    "zng-time",

    # view:
    "zng-view-api",
    "zng-view",
    "zng-view-prebuilt",

    # app:
    "zng-app-proc-macros",
    "zng-app",
    "zng-ext-fs_watcher",
    "zng-ext-config",
    "zng-ext-font",
    "zng-ext-l10n",
    "zng-ext-image",
    "zng-ext-clipboard",
    "zng-ext-window",
    "zng-ext-input",
    "zng-ext-undo",

    # widget:
    "zng-wgt",
    "zng-wgt-access",
    "zng-wgt-transform",
    "zng-wgt-input",
    "zng-wgt-data",
    "zng-wgt-filter",
    "zng-wgt-inspector",
    "zng-wgt-size_offset",
    "zng-wgt-container",
    "zng-wgt-undo",
    "zng-wgt-data_view",
    "zng-wgt-fill",
    "zng-wgt-style",
    "zng-wgt-checkerboard",
    "zng-wgt-window",
    "zng-wgt-layer",
    "zng-wgt-undo_history",
    "zng-wgt-image",
    "zng-wgt-text",
    "zng-wgt-text_input",
    "zng-wgt-button",
    "zng-wgt-stack",
    "zng-wgt-panel",
    "zng-wgt-grid",
    "zng-wgt-wrap",
    "zng-wgt-rule_line",
    "zng-wgt-toggle",
    "zng-wgt-menu",
    "zng-wgt-scroll",
    "zng-wgt-ansi_text",
    "zng-wgt-tooltip",
    "zng-wgt-markdown",
    "zng-wgt-material-icons",
    "zng-wgt-webrender-debug",

    # main
    "zng",

    # tools:
    "zng-l10n-scraper",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
]

exclude = ["dependencies/webrender"]

[profile.dev]
debug = 1

[profile.release-lto]
inherits = "release"
lto = "thin"

[profile.prebuild]
inherits = "release-lto"
