[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[lib]
path = "zero-ui/lib.rs"

[features]
default = ["vp_full"]

# Enable the zero_ui::core::profiler module.
#
# USAGE:
#
# `#[cfg(feature = "app_profiler")` or just use the `profile_scope!` macro.
app_profiler = ["zero-ui-core/app_profiler"]

# Full View-Process, includes `glutin` and the full `webrender` crate.
#
# This feature is enabled by default, disable it if you are building the view-process as a
# separate process. See the `./test-crates/split-vp` workspace for a demo of this.
#
# USAGE:
#
# # To remove in a crate that is the app-process only:
#
# zero-ui = { version = "0.1", default-features = false }
vp_full = ["zero-ui-core/vp_full"]

# # Other Features
#
# ## `doc_nightly`
#
# Activates nightly only `rustdoc` features. The crate is already configured to use this feature
# in "docs.rs" and `do doc`.
# 
# Use `#![cfg_attr(doc_nightly, feature(doc_foo))]` in the `lib.rs` to activate a `rustdoc` feature. Then
# use `#[cfg_attr(doc_nightly, doc(foo))]` in an item.
# 
# Use `RUSTDOCFLAGS="--cfg doc_nightly" cargo +nightly doc` to run `cargo doc` without using `do`.

[dependencies]
# local
zero-ui-core = { path = "zero-ui-core", default-features = false }

# util
paste = "1"
retain_mut = "0.1"
log = "0.4"

[dev-dependencies]
bencher = "0.1"
meval = "0.2"
trybuild = "1"
log = "0.4"
image = "0.23"
# enable test util
zero-ui-core = { path = "zero-ui-core", features = ["test_util"] }

[workspace]
members = ["zero-ui-view-api", "zero-ui-view", "zero-ui-proc-macros", "zero-ui-vp", "zero-ui-core"]
exclude = ["dependencies/webrender"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_nightly"]