[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrender = "0.60.0"
glutin = "0.22.0-alpha3"
gleam = "0.6.18"
font-loader = "0.8.0"
app_units = "0.7.1"
rayon = "1.1.0"
log = "0.4.8"
fern = "0.5.8"
winapi = "0.3.8"
once_cell = "1.2.0"
fnv = "1.0.6"
derive-new = "0.5.8"
zero-ui-derive = { path = "zero-ui-derive" }
retain_mut = "0.1.0"
raw-window-handle = "0.1.2"

[dev-dependencies]
bencher = "0.1.5"

[workspace]

#[[bench]]
#name = "value_changed"
#harness = false