[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Well <well-r@hotmail.com>", "Sam <samu_rodrigues@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrender = "0.60.0"
glutin = "0.22.0-alpha3"
gleam = "0.6.18"
font-loader = "0.8.0"
app_units = "0.7.1"