[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[features]
app_profiler = ["zero-ui-core/app_profiler"]

[dependencies]
# local
zero-ui-core = { path = "zero-ui-core" }

# util
paste = "1.0.4"

# TODO remove?
webrender_api = "0.61.0"

[dev-dependencies]
bencher = "0.1.5"
enclose = "1.1.8"
meval = "0.2.0"

[workspace]
members = ["zero-ui-proc-macros", "zero-ui-core"]

#[[bench]]
#name = "value_changed"
#harness = false