[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[features]
app_profiler = ["serde_json", "lazy_static"]

[dependencies]
# local
zero-ui-macros = { path = "zero-ui-macros" }

# proc-macro-hack
proc-macro-hack = "0.5.15"
proc-macro-nested = "0.1.4"

# core
raw-window-handle = "0.3.3"
winapi = "0.3.8"
glutin = "0.24.0"
gleam = "0.6.17"
webrender = "0.61.0"
font-loader = "0.9.0"
rayon = "1.3.0"

# util
once_cell = "1.3.1"
fnv = "1.0.6"
ego-tree = "0.6.2"
colored = "1.9.3"

# app_profiler only
serde_json = { version = "1.0", optional = true }
lazy_static = { version = "1", optional = true }

[dev-dependencies]
bencher = "0.1.5"
enclose = "1.1.8"
better-panic = "0.2.0"

[workspace]
members = ["zero-ui-macros"]

#[[bench]]
#name = "value_changed"
#harness = false