[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[lib]
path = "zero-ui/lib.rs"

[features]
app_profiler = ["zero-ui-core/app_profiler"]

[dependencies]
# local
zero-ui-core = { path = "zero-ui-core" }

# util
paste = "1"
retain_mut = "0.1"

[dev-dependencies]
bencher = "0.1"
meval = "0.2"
trybuild = "1"
log = "0.4"
async-std = "1.9"
smol = "1.2"
# enable test util
zero-ui-core = { path = "zero-ui-core", features = ["pub_test"] }

[workspace]
members = ["zero-ui-proc-macros", "zero-ui-core"]
