[workspace]
members = [
    # view:
    "zero-ui-view-api", 
    "zero-ui-view", 
    "zero-ui-view-prebuilt", 

    # main:
    "zero-ui-proc-macros", 
    "zero-ui-core", 
    "zero-ui",
    # util:
    "zero-ui-docs",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
    "tests/widget-no-direct-dep/direct-dep",
    "tests/widget-no-direct-dep/no-direct-dep",

    # profile:
    "profile/util",
    "profile/stress",
]

exclude = [
    "dependencies/webrender"
]

[profile.prebuild]
inherits = "release"
lto = true