[workspace]
members = [
    # view:
    "zero-ui-view-api", 
    "zero-ui-view", 
    "zero-ui-view-prebuilt", 

    # main:
    "zero-ui-proc-macros", 
    "zero-ui-core", 
    "zero-ui",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
    "tests/widget-no-direct-dep/direct-dep",
    "tests/widget-no-direct-dep/no-direct-dep",
]

exclude = [
    "dependencies/webrender"
]

[profile.dev.package."*"]
opt-level = 3
[profile.dev.build-override]
opt-level = 3