[workspace]

resolver = "2"

members = [
    # foundation:
    "zero-ui-unique_id",
    "zero-ui-clone_move",
    "zero-ui-handle",
    "zero-ui-txt",
    "zero-ui-units",
    "zero-ui-state_map",
    "zero-ui-app_context",
    "zero-ui-layout",
    "zero-ui-var-proc-macros",
    "zero-ui-var",
    "zero-ui-task-proc-macros",
    "zero-ui-task",
    "zero-ui-color-proc-macros",
    "zero-ui-color",

    # view:
    "zero-ui-view-api",
    "zero-ui-view",
    "zero-ui-view-prebuilt",

    # app:
    "zero-ui-app-proc-macros",
    "zero-ui-app",
    "zero-ui-ext-fs_watcher",
    "zero-ui-ext-config",
    "zero-ui-ext-font",
    "zero-ui-ext-l10n",
    "zero-ui-ext-image",
    "zero-ui-ext-clipboard",
    "zero-ui-ext-window",
    "zero-ui-ext-input",
    "zero-ui-ext-undo",

    # widget:
    "zero-ui-wgt",
    "zero-ui-wgt-access",
    "zero-ui-wgt-transform",
    "zero-ui-wgt-input",
    "zero-ui-wgt-data",
    "zero-ui-wgt-filter",
    "zero-ui-wgt-inspector",
    "zero-ui-wgt-size_offset",
    "zero-ui-wgt-container",
    "zero-ui-wgt-undo",
    "zero-ui-wgt-switch",
    "zero-ui-wgt-view",
    "zero-ui-wgt-fill",
    "zero-ui-wgt-style",
    "zero-ui-wgt-checkerboard",
    "zero-ui-wgt-window",
    "zero-ui-wgt-layer",
    "zero-ui-wgt-undo_history",
    "zero-ui-wgt-image",
    "zero-ui-wgt-text",
    "zero-ui-wgt-text_input",
    "zero-ui-wgt-button",
    "zero-ui-wgt-link",
    "zero-ui-wgt-stack",
    "zero-ui-wgt-panel",
    "zero-ui-wgt-grid",
    "zero-ui-wgt-wrap",
    "zero-ui-wgt-rule_line",
    "zero-ui-wgt-toggle",
    "zero-ui-wgt-menu",
    "zero-ui-wgt-scroll",
    "zero-ui-wgt-ansi_text",
    "zero-ui-wgt-tooltip",
    "zero-ui-wgt-markdown",
    "zero-ui-wgt-material-icons",

    # main
    "zero-ui",

    # tools:
    "zero-ui-l10n-scraper",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
]

exclude = ["dependencies/webrender"]

[profile.dev]
debug = 1

[profile.release-lto]
inherits = "release"
lto = true

[profile.prebuild]
inherits = "release-lto"
