[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[lib]
path = "zero-ui/lib.rs"

[features]
# # Other Features
#
# ## `doc_nightly`
#
# Activates nightly only `rustdoc` features. The crate is already configured to use this feature
# in "docs.rs" and `do doc`.
# 
# Use `#![cfg_attr(doc_nightly, feature(doc_foo))]` in the `lib.rs` to activate a `rustdoc` feature. Then
# use `#[cfg_attr(doc_nightly, doc(foo))]` in an item.
# 
# Use `RUSTDOCFLAGS="--cfg doc_nightly" cargo +nightly doc` to run `cargo doc` without using `do`.

[dependencies]
# local
zero-ui-core = { path = "zero-ui-core" }

# util
paste = "1"
retain_mut = "0.1"
tracing = "0.1"
bitflags = "1"

[profile.dev.package."*"]
opt-level = 3
[profile.dev.build-override]
opt-level = 3

[dev-dependencies]
bencher = "0.1"
meval = "0.2"
trybuild = "1"
image = "0.23"
# enable test util
zero-ui-core = { path = "zero-ui-core", features = ["test_util"] }
zero-ui-view = { path = "zero-ui-view" }
zero-ui-view-prebuilt = { path = "zero-ui-view-prebuilt" }
examples-util = { path = "examples/util" }

[workspace]
members = ["zero-ui-view-api", "zero-ui-view", "zero-ui-view-prebuilt", "zero-ui-proc-macros", "zero-ui-core"]
exclude = ["dependencies/webrender"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_nightly"]