[workspace]

resolver = "2"

members = [
    # foundation:
    "zero-ui-unique_id",
    "zero-ui-clone_move",
    "zero-ui-handle",
    "zero-ui-txt",
    "zero-ui-units",
    "zero-ui-state_map",
    "zero-ui-app_context",
    "zero-ui-layout",
    "zero-ui-var-proc-macros",
    "zero-ui-var",
    "zero-ui-task-proc-macros",
    "zero-ui-task",
    "zero-ui-color-proc-macros",
    "zero-ui-color",

    # view:
    "zero-ui-view-api",
    "zero-ui-view",
    "zero-ui-view-prebuilt",

    # app:
    "zero-ui-app-proc-macros",
    "zero-ui-app",
    "zero-ui-proc-macros",
    "zero-ui-core",
    "zero-ui",
    "zero-ui-material-icons",

    # ext:
    "zero-ui-ext-fs_watcher",
    "zero-ui-ext-config",

    # wgt:
    "zero-ui-wgt",

    # tools:
    "zero-ui-l10n-scraper",

    # examples:
    "examples",
    "examples/util",

    # tests:
    "tests",
    "tests/build",
]

exclude = ["dependencies/webrender"]

[profile.dev]
debug = 1

[profile.release-lto]
inherits = "release"
lto = true

[profile.prebuild]
inherits = "release-lto"
