[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
app_profiler = ["serde_json", "lazy_static"]

[dependencies]
# local
zero-ui-macros = { path = "zero-ui-macros" }

# proc-macro-hack
proc-macro-hack = "0.5.11"
proc-macro-nested = "0.1.3"

# core
raw-window-handle = "0.3.3"
winapi = "0.3.8"
glutin = "0.22.0"
gleam = "0.6.17"
webrender = "0.61.0"
font-loader = "0.8.0"
rayon = "1.3.0"

# util
once_cell = "1.3.1"
fnv = "1.0.6"
retain_mut = "0.1.0"
ego-tree = "0.6.2"

# app_profiler only
serde_json = { version = "1.0", optional = true }
lazy_static = { version = "1", optional = true }

[dev-dependencies]
bencher = "0.1.5"

[workspace]
members = ["zero-ui-macros"]

#[[bench]]
#name = "value_changed"
#harness = false