[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[lib]
path = "zero-ui/lib.rs"

[features]
app_profiler = ["zero-ui-core/app_profiler"]

[dependencies]
# local
zero-ui-core = { path = "zero-ui-core" }

# util
paste = "1.0.4"

[dev-dependencies]
bencher = "0.1.5"
enclose = "1.1.8"
meval = "0.2.0"
serial_test = "0.5.1"
trybuild = "1.0.41"
stderrlog = "0.5.1"
log = "0.4"

[workspace]
members = ["zero-ui-proc-macros", "zero-ui-core"]
