[package]
name = "zng-wgt-input"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-input"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-transform = { path = "../zng-wgt-transform" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-window = { path = "../zng-ext-window" }
zng-app = { path = "../zng-app" }
zng-view-api = { path = "../zng-view-api" }
zng-ext-clipboard = { path = "../zng-ext-clipboard" }
