[package]
name = "zng-l10n-scraper"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
rayon = "1"
glob = "0.3"
rustc_lexer = "0.1"
clap = { version = "4", features = ["derive"] }
fluent-pseudo = "0.3"