[package]
name = "zero-ui-state_map"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"


[dependencies]
zero-ui-unique_id = { path = "../zero-ui-unique_id" }

bytemuck = { version = "1" }
pretty-type-name = "1"