[package]
name = "test-widget-no-direct-dep"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>"]
edition = "2018"

[dependencies]
custom-widget = { path = "custom-widget" }

[workspace]
members = ["custom-widget"]