[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[features]
default = ["ipc", "debug_default"]

# Enables pre-build views and connecting to views running in another process.
# 
# Enabled by default.
ipc = ["zero-ui-app/ipc"]

# Enables http tasks.
http = ["zero-ui-task/http", "zero-ui-wgt/http", "zero-ui-ext-image/http"]

# Enable the `dyn_*`, `inspector` features for debug builds only.
#
# Enabled by default.
debug_default = [
    "zero-ui-app/debug_default",
    "zero-ui-wgt-inspector/debug_default",
    "zero-ui-wgt-scroll/debug_default",
    "zero-ui-wgt-window/debug_default",
]

# Use more dynamic dispatch at the node level by enabling `UiNode::cfg_boxed` to box.
#
# This speeds-up compilation time at the cost of runtime.
dyn_node = ["zero-ui-app/dyn_node"]

# Instrument each property and widget instance with "Inspector" nodes and
# extend windows to be inspected on Ctrl+Shift+I.
inspector = ["zero-ui-app/inspector", "zero-ui-wgt-inspector/live"]

# Use dynamic dispatch at the app-extension level.
#
# This speeds-up compilation time at the cost of runtime.
dyn_app_extension = ["zero-ui-app/dyn_app_extension"]

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = [
    "zero-ui-wgt/dyn_closure",
    "zero-ui-wgt-scroll/dyn_closure",
    "zero-ui-wgt-window/dyn_closure",
]

# Test utilities.
#
# USAGE:
#
# Build with this feature to use the core test helper types that show
# in the documentation.
test_util = ["zero-ui-app/test_util", "zero-ui-ext-window/test_util"]

# Allows multiple app instances per-process.
#
# This feature allows multiple apps, one app per thread at a time. The `LocalContext` tracks
# what app is currently running in each thread and `app_local!` statics switch to the value of each app
# depending on the current thread.
#
# Not enabled by default, but enabled by `feature="test_util"`.
multi_app = ["zero-ui-app/multi_app"]

# Instrument every widget outer-most node to trace UI methods.
trace_widget = ["zero-ui-app/trace_widget"]

# Instrument every property and intrinsic node to trace UI methods.
#
# Note that this can cause very large trace files and bad performance.
trace_wgt_item = ["zero-ui-app/trace_wgt_item"]

# Spawns a thread on app creation that checks and prints `parking_lot` deadlocks.
#
# Not enabled by default.
deadlock_detection = ["zero-ui-app/deadlock_detection"]

# Embed hyphenation dictionaries for all supported languages.
#
# If enabled some 2.8MB of data is embedded, you can provide an alternative dictionary source using the 
# `Hyphenation::dictionary_source` method.
#
# Not enabled by default.
hyphenation_embed_all = ["zero-ui-ext-font/hyphenation_embed_all"]

# Include all Material Icons icon sets in the default app.
#
# Not enabled by default.
material_icons = [
    "material_icons_outlined",
    "material_icons_filled",
    "material_icons_rounded",
    "material_icons_sharp",
]
# Material Icons Outlined icon set.
#
# If enabled some icons of this set are used for some of the commands.
#
# Not enabled by default.
material_icons_outlined = ["zero-ui-wgt-material-icons", "zero-ui-wgt-material-icons/embedded", "zero-ui-wgt-material-icons/outlined"]

# Material Icons Filled icon set.
#
# Not enabled by default.
material_icons_filled = ["zero-ui-wgt-material-icons", "zero-ui-wgt-material-icons/embedded", "zero-ui-wgt-material-icons/filled"]

# Material Icons Rounded icon set.
#
# Not enabled by default.
material_icons_rounded = ["zero-ui-wgt-material-icons", "zero-ui-wgt-material-icons/embedded", "zero-ui-wgt-material-icons/rounded"]

# Material Icons Sharp icon set.
#
# Not enabled by default.
material_icons_sharp = ["zero-ui-wgt-material-icons", "zero-ui-wgt-material-icons/embedded", "zero-ui-wgt-material-icons/sharp"]

# Enable TOML configs.
toml = ["zero-ui-ext-config/toml"]
# Enable RON configs.
ron = ["zero-ui-ext-config/ron"]
# Enable YAML configs.
yaml = ["zero-ui-ext-config/yaml"]

[dependencies]
# foundation
zero-ui-clone_move = { path = "../zero-ui-clone_move" }
zero-ui-txt = { path = "../zero-ui-txt" }
zero-ui-state_map = { path = "../zero-ui-state_map" }
zero-ui-app_context = { path = "../zero-ui-app_context" }
zero-ui-layout = { path = "../zero-ui-layout" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-task = { path = "../zero-ui-task" }
zero-ui-color = { path = "../zero-ui-color" }

# view
zero-ui-view-api = { path = "../zero-ui-view-api" }

# app
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-ext-fs_watcher = { path = "../zero-ui-ext-fs_watcher" }
zero-ui-ext-config = { path = "../zero-ui-ext-config" }
zero-ui-ext-font = { path = "../zero-ui-ext-font" }
zero-ui-ext-l10n = { path = "../zero-ui-ext-l10n" }
zero-ui-ext-image = { path = "../zero-ui-ext-image" }
zero-ui-ext-clipboard = { path = "../zero-ui-ext-clipboard" }
zero-ui-ext-window = { path = "../zero-ui-ext-window" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-ext-undo = { path = "../zero-ui-ext-undo" }

# widgets
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-transform = { path = "../zero-ui-wgt-transform" }
zero-ui-wgt-input = { path = "../zero-ui-wgt-input" }
zero-ui-wgt-data = { path = "../zero-ui-wgt-data" }
zero-ui-wgt-filter = { path = "../zero-ui-wgt-filter" }
zero-ui-wgt-size_offset = { path = "../zero-ui-wgt-size_offset" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }
zero-ui-wgt-undo = { path = "../zero-ui-wgt-undo" }
zero-ui-wgt-switch = { path = "../zero-ui-wgt-switch" }
zero-ui-wgt-view = { path = "../zero-ui-wgt-view" }
zero-ui-wgt-fill = { path = "../zero-ui-wgt-fill" }
zero-ui-wgt-style = { path = "../zero-ui-wgt-style" }
zero-ui-wgt-checkerboard = { path = "../zero-ui-wgt-checkerboard" }
zero-ui-wgt-window = { path = "../zero-ui-wgt-window" }
zero-ui-wgt-layer = { path = "../zero-ui-wgt-layer" }
zero-ui-wgt-undo_history = { path = "../zero-ui-wgt-undo_history" }
zero-ui-wgt-image = { path = "../zero-ui-wgt-image" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }
zero-ui-wgt-text_input = { path = "../zero-ui-wgt-text_input" }
zero-ui-wgt-button = { path = "../zero-ui-wgt-button" }
zero-ui-wgt-link = { path = "../zero-ui-wgt-link" }
zero-ui-wgt-stack = { path = "../zero-ui-wgt-stack" }
zero-ui-wgt-panel = { path = "../zero-ui-wgt-panel" }
zero-ui-wgt-grid = { path = "../zero-ui-wgt-grid" }
zero-ui-wgt-wrap = { path = "../zero-ui-wgt-wrap" }
zero-ui-wgt-rule_line = { path = "../zero-ui-wgt-rule_line" }
zero-ui-wgt-toggle = { path = "../zero-ui-wgt-toggle" }
zero-ui-wgt-menu = { path = "../zero-ui-wgt-menu" }
zero-ui-wgt-scroll = { path = "../zero-ui-wgt-scroll" }
zero-ui-wgt-ansi_text = { path = "../zero-ui-wgt-ansi_text" }
zero-ui-wgt-tooltip = { path = "../zero-ui-wgt-tooltip" }
zero-ui-wgt-markdown = { path = "../zero-ui-wgt-markdown" }
zero-ui-wgt-inspector = { path = "../zero-ui-wgt-inspector" }

zero-ui-wgt-material-icons = { path = "../zero-ui-wgt-material-icons", default-features = false, optional = true }

[dev-dependencies]
# used in the README.md and lib.rs doc examples.
zero-ui-view = { path = "../zero-ui-view" }
