[package]
name = "zero-ui"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[features]
default = ["ipc", "http", "debug_default"]

# Enables pre-build views and connecting to views running in another process.
# 
# Enabled by default.
ipc = ["zero-ui-core/ipc"]

# Enables http tasks.
#
# Enabled by default.
http = ["zero-ui-core/http"]

# Signal the `zero-ui-core` build script to enable the `dyn_*` and `inspector` features for debug builds.
#
# Enabled by default.
debug_default = ["zero-ui-core/debug_default"]

# Use dynamic dispatch at the node level by placing each property node in a `BoxedUiNode` and enabling `UiNode::cfg_boxed`.
#
# This speeds-up compilation time at the cost of runtime.
dyn_node = ["zero-ui-core/dyn_node"]

# Instrument each property and widget instance with "Inspector" nodes.
inspector = ["zero-ui-core/inspector"]

# Use dynamic dispatch at the app-extension level.
#
# This speeds-up compilation time at the cost of runtime.
dyn_app_extension = ["zero-ui-core/dyn_app_extension"]

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = ["zero-ui-core/dyn_closure"]

# like cfg(test) but also visible in docs and integration tests.
#
# USAGE:
#
# Build with this feature to use the core test helper types that show
# in the documentation.
test_util = ["zero-ui-core/test_util"]

# Instrument every widget outer-most node to trace UI methods.
trace_widget = ["zero-ui-core/trace_widget"]

# Instrument every property and intrinsic node to trace UI methods.
#
# Note that this can cause very large trace files and bad performance.
trace_wgt_item = ["zero-ui-core/trace_wgt_item"]

# Spawns a thread on app creation that checks and prints `parking_lot` deadlocks.
#
# Not enabled by default.
deadlock_detection = ["zero-ui-core/deadlock_detection"]

[dependencies]
# local
zero-ui-core = { path = "../zero-ui-core", default-features = false }

# util
paste = "1"
tracing = "0.1"
bitflags = "1"
linear-map = "1"
serde = "1"
pretty-type-name = "1"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "zero-ui-core/src/doc/html-in-header.html" ]