[package]
name = "zng-wgt-scroll"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-size_offset = { path = "../zng-wgt-size_offset" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-app = { path = "../zng-app" }
zng-ext-window = { path = "../zng-ext-window" }
zng-ext-input = { path = "../zng-ext-input" }
zng-var = { path = "../zng-var" }
zng-color = { path = "../zng-color" }

serde = { version = "1", features = ["derive"] }
atomic = "0.6"
bitflags = "2"
bytemuck = "1"
euclid = "0.22"
parking_lot = "0.12"
tracing = "0.1"
