[package]
name = "zng-ext-image"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-image"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
http = ["zng-task/http"]

[dependencies]
zng-app-context = { path = "../zng-app-context" }
zng-unique-id = { path = "../zng-unique-id" }
zng-clone-move = { path = "../zng-clone-move" }
zng-app = { path = "../zng-app" }
zng-view-api = { path = "../zng-view-api" }
zng-txt = { path = "../zng-txt" }
zng-var = { path = "../zng-var" }
zng-task = { path = "../zng-task" }
zng-layout = { path = "../zng-layout" }
zng-color = { path = "../zng-color" }
zng-state-map = { path = "../zng-state-map" }

serde = "1"
once_cell = "1"
parking_lot = "0.12"
tracing = "0.1"
base64 = "0.22"
sha2 = "0.10"