[package]
name = "zero-ui-vp"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]

# windowing
glutin = { version = "0.27", features = ["serde"] }

# render
webrender = "0.61"
gleam = "0.6.17" #version required by webrender

# ipc
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
parking_lot = "0.11"
ipc-channel = "0.15"
duct = "0.13"

# util
winapi = "0.3"
log = "0.4"
is_main_thread = "0.1"
flume = "0.10"