[package]
name = "zero-ui-view"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
zero-ui-view-api = { path = "../zero-ui-view-api" }
webrender = { path = "../dependencies/webrender/webrender" }
log = "0.4"
gleam = "0.13.1"
glutin = "0.27"
flume = "0.10"
is_main_thread = "0.1"
image = "0.23"
rustc-hash = "1"
rayon = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "errhandlingapi", "windef", "minwindef", "commctrl", "basetsd", "winerror", "combaseapi", "shobjidl_core", "wtypesbase"] }
