[package]
name = "zero-ui-view"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["ipc"]

# Enables pre-build and init as view-process.
#
# If this is enabled all communication with the view is serialized/deserialized, 
# even if is running in same-process mode.
#
# Enabled by default.
ipc = ["zero-ui-view-api/ipc"]

# Enables software renderer fallback.
#
# If enabled and a native OpenGL 3.2 driver is not available the `swgl` software renderer is used.
#
# The `clang-cl` dependency is required to build with this feature on Windows, you can install a copy
# by installing LLVM (https://releases.llvm.org/) and adding the installation
# to the path with something like `set PATH=%PATH%;C:\Program Files\LLVM\bin`.
# Then `set CC=clang-cl` and `set CXX=clang-cl`.
#
# Enabled by default.
# software = ["swgl"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
zero-ui-view-api = { path = "../zero-ui-view-api", default-features = false }
webrender = { path = "../dependencies/webrender/webrender" }
# swgl = { path = "../dependencies/webrender/swgl", optional = true }
tracing = "0.1"
gleam = "0.13.1" # matches webrender
glutin = "0.28.0"
flume = "0.10"
is_main_thread = "0.1"
image = "0.23"
img-parts = "0.2"
byteorder = "1"
rustc-hash = "1"
rayon = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "errhandlingapi", "windef", "minwindef", "commctrl", "basetsd", "winerror", "combaseapi", "shobjidl_core", "wtypesbase"] }
