[package]
name = "zng-wgt-image"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-app = { path = "../zng-app" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-ext-image = { path = "../zng-ext-image" }
zng-ext-window = { path = "../zng-ext-window" }
zng-wgt-window = { path = "../zng-wgt-window" }
zng-wgt-stack = { path = "../zng-wgt-stack" }

serde = { version = "1", features = ["derive"] }
