[package]
name = "zng-wgt-image"
version = "0.2.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-image"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.0" }
zng-ext-image = { path = "../zng-ext-image", version = "0.2.0" }
zng-ext-window = { path = "../zng-ext-window", version = "0.2.0" }
zng-wgt-window = { path = "../zng-wgt-window", version = "0.2.0" }
zng-wgt-stack = { path = "../zng-wgt-stack", version = "0.2.0" }

serde = { version = "1", features = ["derive"] }
