[package]
name = "zero-ui-wgt-tooltip"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zero-ui-app/README.md"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-layer = { path = "../zero-ui-wgt-layer" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }
zero-ui-wgt-fill = { path = "../zero-ui-wgt-fill" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }
zero-ui-wgt-style = { path = "../zero-ui-wgt-style" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
