[package]
name = "zng-wgt-undo"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-ext-undo = { path = "../zng-ext-undo" }