[package]
name = "zero-ui-wgt-scroll"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-fill = { path = "../zero-ui-wgt-fill" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-size_offset = { path = "../zero-ui-wgt-size_offset" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }
zero-ui-wgt-input = { path = "../zero-ui-wgt-input" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-ext-window = { path = "../zero-ui-ext-window" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-color = { path = "../zero-ui-color" }

serde = { version = "1", features = ["derive"] }
atomic = "0.6"
bitflags = "2"
bytemuck = "1"
euclid = "0.22"
parking_lot = "0.12"
tracing = "0.1"
