[package]
name = "zng-ext-clipboard"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-app-context = { path = "../zng-app-context" }
zng-app = { path = "../zng-app" }
zng-var = { path = "../zng-var" }
zng-view-api = { path = "../zng-view-api" }
zng-txt = { path = "../zng-txt" }
zng-ext-image = { path = "../zng-ext-image" }

tracing = "0.1"