[package]
name = "zng-wgt-stack"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]
debug_default = []
dyn_closure = []

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset" }
zng-app = { path = "../zng-app" }
zng-layout = { path = "../zng-layout" }
zng-var = { path = "../zng-var" }

euclid = "0.22"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"