[package]
name = "zng-ext-input"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-app_context = { path = "../zng-app_context" }
zng-clone_move = { path = "../zng-clone_move" }
zng-view-api = { path = "../zng-view-api" }
zng-app = { path = "../zng-app" }
zng-txt = { path = "../zng-txt" }
zng-var = { path = "../zng-var" }
zng-layout = { path = "../zng-layout" }
zng-handle = { path = "../zng-handle" }
zng-state_map = { path = "../zng-state_map" }
zng-unique_id = { path = "../zng-unique_id" }
zng-ext-window = { path = "../zng-ext-window" }

tracing = "0.1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
bitflags = "2"
atomic = "0.6"