[package]
name = "zng-wgt"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]

# Signal the build script to enable the `dyn_*`, `inspector` and `trace_widget` features for debug builds.
#
# Enabled by default.
debug_default = ["zng-var/debug_default"]

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = ["zng-var/dyn_closure"]

# Enable web tasks.
http = ["zng-task/http"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move" }
zng-app = { path = "../zng-app" }
zng-color = { path = "../zng-color" }
zng-app-context = { path = "../zng-app-context" }
zng-var = { path = "../zng-var" }
zng-state-map = { path = "../zng-state-map" }
zng-layout = { path = "../zng-layout" }
zng-task = { path = "../zng-task" }
zng-txt = { path = "../zng-txt" }
zng-unique-id = { path = "../zng-unique-id" }

paste = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
pretty-type-name = "1"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "zng-app/doc/html-in-header.html"]
