[package]
name = "zero-ui-l10n-scraper"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
rayon = "1"
glob = "0.3"
rustc_lexer = "0.1"
clap = { version = "4", features = ["derive"] }