[package]
name = "zng-ext-font"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
test_util = ["zng-app/test_util"]
hyphenation_embed_all = ["hyphenation/embed_all"]

[dependencies]
zng-clone_move = { path = "../zng-clone_move" }
zng-app_context = { path = "../zng-app_context" }
zng-app = { path = "../zng-app" }
zng-txt = { path = "../zng-txt" }
zng-view-api = { path = "../zng-view-api" }
zng-ext-l10n = { path = "../zng-ext-l10n" }
zng-var = { path = "../zng-var" }
zng-task = { path = "../zng-task" }
zng-layout = { path = "../zng-layout" }
zng-color = { path = "../zng-color" }

serde = "1"
unicase = "2"
font-kit = "0.13"
harfbuzz_rs = "2"
parking_lot = "0.12"
byteorder = "1"
icu_properties = "1"
bitflags = "2"
tracing = "0.1"
paste = "1"
num_enum = "0.7"
hyphenation = "0.8"
regex = "1"
unicode-bidi = "0.3"
unicode-linebreak = "0.1"
unicode-segmentation = "1"
unic-langid = "0.9"
smallvec = { version = "1", features = ["const_new", "serde"] }
hashbrown = "0.14"
pathfinder_geometry = "0.5"