[package]
name = "zng-wgt-undo_history"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-button = { path = "../zng-wgt-button" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-scroll = { path = "../zng-wgt-scroll" }
zng-wgt-stack = { path = "../zng-wgt-stack" }
zng-wgt-style = { path = "../zng-wgt-style" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-size_offset = { path = "../zng-wgt-size_offset" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-ext-undo = { path = "../zng-ext-undo" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-l10n = { path = "../zng-ext-l10n" }