[package]
name = "zero-ui-core"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"

[features]
# Enable the zero_ui_core::profiler module.
#
# USAGE:
#
# `#[cfg(feature = "app_profiler")` or just use the `profile_scope!` macro.
app_profiler = []

# like cfg(test) but also visible in docs and integration tests.
#
# USAGE:
#
# For zero-ui-core maintainers, use `#[cfg(feature="test_util")]` in the helper types and places where
# the types are used. Use `do` to run integration tests.
#
# For external dependents, build with this feature to use the test helper types that show
# in the documentation.
test_util = []

# # Other Features
#
# ## `doc_nightly`
#
# Activates nightly only `rustdoc` features. The crate is already configured to use this feature
# in "docs.rs" and `do doc`.
# 
# Use `#![cfg_attr(doc_nightly, feature(doc_foo))]` in the `lib.rs` to activate a `rustdoc` feature. Then
# use `#[cfg_attr(doc_nightly, doc(foo))]` in an item.
# 
# Use `RUSTDOCFLAGS="--cfg doc_nightly" cargo +nightly doc` to run `cargo doc` without using `do`.

[dependencies]
# local
zero-ui-proc-macros = { path = "../zero-ui-proc-macros" }

# windowing
glutin = "0.27"
winapi = "0.3"

# text
font-kit = "0.10"
unicode-script = "0.5"
unicase = "2"
rustybuzz = "0.4"
xi-unicode = "0.3"

# render
zero-ui-wr = { path = "../zero-ui-wr" }
webrender_api = "0.61"
image = "0.23"

# task
flume = "0.10"
rayon = "1"
blocking = "1"
parking_lot = "0.11"
futures-timer = "3"
isahc = { version = "1", features = ["cookies", "json"] }
pollster = "0.2"
async-trait = "0.1"
futures-lite = "1"

# util
bitflags = "1"
paste = "1"
rustc-hash = "1"
colored = "2"
array-init = "2"
derive_more = "0.99"
ego-tree = "0.6"
retain_mut = "0.1"
once_cell = "1.5"
is_main_thread = "0.1"
img-parts = "0.2"
byteorder = "1"
log = "0.4"
unsafe-any = "0.4"
linear-map = "1"
rand = "0.8"
lcms2 = "5"


# serde
serde = "1"
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_nightly"]