[package]
name = "zero-ui-core"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[features]
app_profiler = ["serde_json", "lazy_static"]

[dependencies]
# local
zero-ui-proc-macros = { path = "../zero-ui-proc-macros" }

# windowing
glutin = "0.26.0"
winapi = "0.3.9"

# text
font-kit = "0.8.0" #version required by harfbuzz_rs
unicode-script = "0.5.2"
unicase = "2.6.0"
harfbuzz_rs = "1.2.0"
xi-unicode = "0.3.0"

# render
webrender = "0.61.0"
euclid = "0.20.7" #version required by webrender
gleam = "0.6.17" #version required by webrender
image = "0.23.12"

# sync
flume = "0.10.1"
rayon = "1.5.0"
async-global-executor = "2.0.1"

# util
bitflags = "1.2.1"
paste = "1.0.4"
fnv = "1.0.7"
colored = "2.0.0"
array-init = "1.0.0"
derive_more = "0.99.11"
ego-tree = "0.6.2"
retain_mut = "0.1.2"
once_cell = "1.5.2"

# app_profiler only
serde_json = { version = "1.0", optional = true }
lazy_static = { version = "1", optional = true }

[dev-dependencies]
serial_test = "0.5.1"