[package]
name = "zero-ui-core"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[features]
# Enable the zero_ui_core::profiler module.
#
# USAGE:
#
# `#[cfg(feature = "app_profiler")` or just use the `profile_scope!` macro.
app_profiler = ["serde_json", "lazy_static"]

# like cfg(test) but also visible in docs and integration tests.
#
# USAGE:
#
# For zero-ui-core maintainers, use `#[cfg(feature="pub_test")]` in the helper types and places where
# the types are used. Use `do` to run integration tests.
#
# For external dependents, build with this feature to use the test helper types that show
# in the documentation.
pub_test = []

[dependencies]
# local
zero-ui-proc-macros = { path = "../zero-ui-proc-macros" }

# windowing
glutin = "0.26"
winapi = "0.3"

# text
font-kit = "0.10"
unicode-script = "0.5"
unicase = "2"
rustybuzz = "0.3"
xi-unicode = "0.3"

# render
webrender = "0.61"
gleam = "0.6.17" #version required by webrender
image = "0.23"

# sync
flume = "0.10"
rayon = "1"
blocking = "1"

# util
bitflags = "1"
paste = "1"
fnv = "1"
colored = "2"
array-init = "2"
derive_more = "0.99"
ego-tree = "0.6"
retain_mut = "0.1"
once_cell = "1.5"
is_main_thread = "0.1"
img-parts = "0.2"
byteorder = "1"
log = "0.4"
unsafe-any = "0.4"

# app_profiler only
serde_json = { version = "1", optional = true }
lazy_static = { version = "1", optional = true }
