[package]
name = "zng-ext-fs_watcher"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
zng-app_context = { path = "../zng-app_context" }
zng-app = { path = "../zng-app" }
zng-clone_move = { path = "../zng-clone_move" }
zng-var = { path = "../zng-var" }
zng-txt = { path = "../zng-txt" }
zng-unit = { path = "../zng-unit" }
zng-handle = { path = "../zng-handle" }
zng-task = { path = "../zng-task" }

walkdir = "2"
serde = "1"
tracing = "0.1"
fs4 = "0.8"
glob = "0.3"
notify = "6"
path-absolutize = "3"
atomic = "0.6"
parking_lot = "0.12"
flume = "0.11"

serde_json = { version = "1", optional = true }
toml = { version = "0.8", optional = true, features = ["preserve_order"] }
ron = { version = "0.8", optional = true, features = ["indexmap"] }
serde_yaml = { version = "0.9", optional = true }