[package]
name = "zng-var"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]

# Signal the build script to enable the `dyn_*` features for debug builds.
#
# Enabled by default.
debug_default = []

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = []

[dependencies]
zng-var-proc-macros = { path = "../zng-var-proc-macros" }

zng-txt = { path = "../zng-txt" }
zng-unit = { path = "../zng-unit" }
zng-app-context = { path = "../zng-app-context" }
zng-time = { path = "../zng-time" }
zng-clone-move = { path = "../zng-clone-move" }
zng-handle = { path = "../zng-handle" }

bitflags = { version = "2", features = ["serde"] }
bytemuck = { version = "1", features = ["derive"] }
parking_lot = "0.12"
tracing = "0.1"
take_mut = "0.2"
pretty-type-name = "1"
