[package]
name = "zero-ui-wgt-inspector"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-view-api = { path = "../zero-ui-view-api" }
zero-ui-ext-window = { path = "../zero-ui-ext-window" }
zero-ui-units = { path = "../zero-ui-units" }

serde = { version = "1", features = ["derive"] }
tracing = "0.1"