[package]
name = "profile-util"
version = "0.1.0"
edition = "2021"

[features]
default = ["deflate"]
deflate = ["flate2"]

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
rustc-hash = "1"
v_jsonescape = "0.7"
flate2 = { version = "1", optional = true }
parking_lot = "0.12"