[package]
name = "direct-dep"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[dependencies]
zero-ui = { path = "../../../../zero-ui" }