[package]
name = "zng-wgt-grid"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-size_offset = { path = "../zng-wgt-size_offset" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-layout = { path = "../zng-layout" }

tracing = "0.1"