[package]
name = "zng-wgt-grid"
version = "0.2.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-grid"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.0" }
zng-wgt-access = { path = "../zng-wgt-access", version = "0.2.0" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset", version = "0.2.0" }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.2.0" }
zng-layout = { path = "../zng-layout", version = "0.2.0" }

tracing = "0.1"
