[package]
name = "zng-wgt-inspector"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]
debug_default = []
live = []

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-app = { path = "../zng-app" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-font = { path = "../zng-ext-font" }
zng-ext-config = { path = "../zng-ext-config", default-features = false }
zng-ext-l10n = { path = "../zng-ext-l10n" }
zng-view-api = { path = "../zng-view-api" }
zng-ext-window = { path = "../zng-ext-window" }
zng-wgt-window = { path = "../zng-wgt-window" }
zng-wgt-button = { path = "../zng-wgt-button" }
zng-wgt-toggle = { path = "../zng-wgt-toggle" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-text-input = { path = "../zng-wgt-text-input" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-scroll = { path = "../zng-wgt-scroll" }
zng-wgt-stack = { path = "../zng-wgt-stack" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset" }
zng-wgt-wrap = { path = "../zng-wgt-wrap" }
zng-wgt-filter = { path = "../zng-wgt-filter" }
zng-wgt-rule-line = { path = "../zng-wgt-rule-line" }
zng-wgt-ansi-text = { path = "../zng-wgt-ansi-text" }
zng-wgt-style = { path = "../zng-wgt-style" }
zng-layout = { path = "../zng-layout" }
zng-var = { path = "../zng-var" }
zng-color = { path = "../zng-color" }

serde = { version = "1", features = ["derive"] }
tracing = "0.1"
parking_lot = "0.12"
