[package]
name = "zng-ext-undo"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-undo"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.2.0" }
zng-app-context = { path = "../zng-app-context", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-txt = { path = "../zng-txt", version = "0.2.0" }
zng-state-map = { path = "../zng-state-map", version = "0.2.0" }
zng-ext-input = { path = "../zng-ext-input", version = "0.2.0" }

atomic = "0.6"
parking_lot = "0.12"
