[package]
name = "zng-ext-undo"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-undo"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-clone-move = { path = "../zng-clone-move" }
zng-app-context = { path = "../zng-app-context" }
zng-app = { path = "../zng-app" }
zng-var = { path = "../zng-var" }
zng-txt = { path = "../zng-txt" }
zng-state-map = { path = "../zng-state-map" }
zng-ext-input = { path = "../zng-ext-input" }

atomic = "0.6"
parking_lot = "0.12"