[package]
name = "zero-ui-wgt-text"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-app_context = { path = "../zero-ui-app_context" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-color = { path = "../zero-ui-color" }
zero-ui-layout = { path = "../zero-ui-layout" }
zero-ui-wgt-data = { path = "../zero-ui-wgt-data" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-size_offset = { path = "../zero-ui-wgt-size_offset" }
zero-ui-wgt-layer = { path = "../zero-ui-wgt-layer" }
zero-ui-wgt-scroll = { path = "../zero-ui-wgt-scroll" }
zero-ui-ext-undo = { path = "../zero-ui-ext-undo" }
zero-ui-ext-font = { path = "../zero-ui-ext-font" }
zero-ui-ext-l10n = { path = "../zero-ui-ext-l10n" }
zero-ui-view-api = { path = "../zero-ui-view-api" }
zero-ui-ext-clipboard = { path = "../zero-ui-ext-clipboard" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-ext-window = { path = "../zero-ui-ext-window" }

atomic = "0.6"
tracing = "0.1"
serde = "1"
parking_lot = "0.12"
bitflags = "2"
bytemuck = "1"
euclid = "0.22"