[package]
name = "zng-wgt-window"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]
debug_default = ["zng-wgt/debug_default"]
dyn_closure = ["zng-wgt/dyn_closure"]

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-app = { path = "../zng-app" }
zng-ext-window = { path = "../zng-ext-window" }
zng-ext-config = { path = "../zng-ext-config", default-features = false }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-l10n = { path = "../zng-ext-l10n" }
zng-var = { path = "../zng-var" }
zng-color = { path = "../zng-color" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-layer = { path = "../zng-wgt-layer" }

serde = { version = "1", features = ["derive"] }
paste = "1"
parking_lot = "0.12"
euclid = "0.22"