[package]
name = "zero-ui-view-api"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["ipc"]

# Enables creation of separate or pre-build view, enabled by default.
#
# When this is enabled communication with the view is (de)serialized which can add a 
# minor cost, something like a 1ms per 3MB frame request.
ipc = ["ipc-channel", "duct"]

[dependencies]
webrender_api = { path = "../dependencies/webrender/webrender_api" }
serde = { version = "1.0", features = ["derive"] }
ipc-channel = { version = "0.16", optional = true }
duct = { version = "0.13", optional = true }

tracing = "0.1"
flume = { version = "0.10", default-features  = false }
bitflags = "1"
num-traits = "0.2"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_nightly"]