[package]
name = "zero-ui-wgt-panel"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-wrap = { path = "../zero-ui-wgt-wrap" }
zero-ui-wgt-view = { path = "../zero-ui-wgt-view" }
zero-ui-app = { path = "../zero-ui-app" }