[package]
name = "zng-wgt-button"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-button"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-var = { path = "../zng-var" }
zng-app = { path = "../zng-app" }
zng-ext-font = { path = "../zng-ext-font" }
zng-wgt = { path = "../zng-wgt" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-style = { path = "../zng-wgt-style" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-filter = { path = "../zng-wgt-filter" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-tooltip = { path = "../zng-wgt-tooltip" }