[package]
name = "zero-ui-wgt-markdown"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
# Enable web links and images.
http = ["zero-ui-wgt/http"]

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }
zero-ui-wgt-scroll = { path = "../zero-ui-wgt-scroll" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }
zero-ui-wgt-button = { path = "../zero-ui-wgt-button" }
zero-ui-wgt-link = { path = "../zero-ui-wgt-link" }
zero-ui-wgt-stack = { path = "../zero-ui-wgt-stack" }
zero-ui-wgt-wrap = { path = "../zero-ui-wgt-wrap" }
zero-ui-wgt-rule_line = { path = "../zero-ui-wgt-rule_line" }
zero-ui-wgt-view = { path = "../zero-ui-wgt-view" }
zero-ui-wgt-grid = { path = "../zero-ui-wgt-grid" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-ansi_text = { path = "../zero-ui-wgt-ansi_text" }
zero-ui-wgt-layers = { path = "../zero-ui-wgt-layers" }
zero-ui-wgt-size_offset = { path = "../zero-ui-wgt-size_offset" }
zero-ui-wgt-transform = { path = "../zero-ui-wgt-transform" }
zero-ui-wgt-input = { path = "../zero-ui-wgt-input" }
zero-ui-wgt-image = { path = "../zero-ui-wgt-image" }
zero-ui-wgt-tooltip = { path = "../zero-ui-wgt-tooltip" }
zero-ui-wgt-fill = { path = "../zero-ui-wgt-fill" }
zero-ui-wgt-filters = { path = "../zero-ui-wgt-filters" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-ext-image = { path = "../zero-ui-ext-image" }
zero-ui-ext-font = { path = "../zero-ui-ext-font" }
zero-ui-app = { path = "../zero-ui-app" }

pulldown-cmark = "0.9"
path-absolutize = "3"
html-escape = "0.2"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
