[package]
name = "zng-color"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-color-proc-macros = { path = "../zng-color-proc-macros" }
zng-layout = { path = "../zng-layout" }
zng-app_context = { path = "../zng-app_context" }
zng-var = { path = "../zng-var" }
zng-view-api = { path = "../zng-view-api" }

paste = "1"
serde = "1"