[package]
name = "zero-ui-wgt-data"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-color = { path = "../zero-ui-color" }
zero-ui-var = { path = "../zero-ui-var" }

serde = { version = "1", features = ["derive"] }
