[package]
name = "zero-ui-proc-macros"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.10"
syn = { version = "1.0.18", features = ["full", "visit-mut", "extra-traits"] }
quote = "1.0.4"

proc-macro-hack = "0.5.15"
proc-macro-crate = "0.1.4"

once_cell = "1.3.1"
uuid = { version = "0.8.1", features = ["v4"] }