[package]
name = "zero-ui-proc-macros"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
syn = { version = "1.0.51", features = ["full", "visit-mut", "extra-traits", "derive"] }
quote = "1.0.7"
proc-macro-crate = "0.1.5"

once_cell = "1.5.2"
uuid = { version = "0.8.1", features = ["v4"] }
heck = "0.3.1"

[build-dependencies]
minifier = "0.0.36"