[package]
name = "zero-ui-proc-macros"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full", "visit-mut", "extra-traits", "derive"] }
quote = "1"

once_cell = "1"

[build-dependencies]
minifier = "0.0.41"
