[package]
name = "web-color-gen"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"

[workspace] # Exclude from main workspace