[package]
name = "web-color-gen"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"

[dependencies]
serde = "1"
serde_json = "1"

[workspace] # Exclude from main workspace