[package]
name = "zero-ui-wgt-material-icons"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zero-ui-app/README.md"

[features]
default = ["embedded", "outlined", "filled", "rounded", "sharp"]

# Embedded font files.
embedded = []

# Outlined icon set.
outlined = []

# Filled icon set.
filled = []

# Rounded icon set.
rounded = []

# Sharp icon set.
sharp = []

[dependencies]
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-ext-font = { path = "../zero-ui-ext-font" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "target/doc/zero-ui-material-icons-extensions.html",
]
