[package]
name = "zng-wgt-material-icons"
version = "0.2.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-material-icons"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
default = ["embedded", "outlined", "filled", "rounded", "sharp"]

# Embedded font files.
embedded = []

# Outlined icon set.
outlined = []

# Filled icon set.
filled = []

# Rounded icon set.
rounded = []

# Sharp icon set.
sharp = []

[dependencies]
zng-app = { path = "../zng-app", version = "0.2.0" }
zng-var = { path = "../zng-var", version = "0.2.0" }
zng-ext-font = { path = "../zng-ext-font", version = "0.2.0" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.2.0" }

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "target/doc/zng-material-icons-extensions.html",
]
