[package]
name = "zng-app_context"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
default = ["debug_default"]

# Allows multiple app instances per-process.
#
# This feature allows multiple apps, one app per thread at a time. The `LocalContext` tracks
# what app is currently running in each thread and `app_local!` statics switch to the value of each app
# depending on the current thread.
multi_app = []

debug_default = []

dyn_closure = []

[dependencies]
zng-unique_id = { path = "../zng-unique_id" }
zng-txt = { path = "../zng-txt" }
parking_lot = "0.12"
hashbrown = { version = "0.14", features = ["rayon"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
bytemuck = { version = "1", features = ["derive"] }
