[package]
name = "no-direct-dep"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[dependencies]
direct-dep = { path = "direct-dep" }

[workspace]
members = ["direct-dep"]