[package]
name = "zng-ext-window"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[features]
test_util = []

[dependencies]
zng-clone-move = { path = "../zng-clone-move" }
zng-unique-id = { path = "../zng-unique-id" }
zng-app-context = { path = "../zng-app-context" }
zng-app = { path = "../zng-app" }
zng-var = { path = "../zng-var" }
zng-txt = { path = "../zng-txt" }
zng-layout = { path = "../zng-layout" }
zng-state-map = { path = "../zng-state-map" }
zng-view-api = { path = "../zng-view-api" }
zng-task = { path = "../zng-task" }
zng-ext-image = { path = "../zng-ext-image" }
zng-color = { path = "../zng-color" }

serde = { version = "1", features = ["derive"] }
bitflags = "2"
atomic = "0.6"
tracing = "0.1"
parking_lot = "0.12"
