[package]
name = "zng-ext-window"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-ext-window"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[features]
test_util = []

[dependencies]
zng-clone-move = { path = "../zng-clone-move", version = "0.1.0" }
zng-unique-id = { path = "../zng-unique-id", version = "0.1.0" }
zng-app-context = { path = "../zng-app-context", version = "0.1.0" }
zng-app = { path = "../zng-app", version = "0.1.0" }
zng-var = { path = "../zng-var", version = "0.1.0" }
zng-txt = { path = "../zng-txt", version = "0.1.0" }
zng-layout = { path = "../zng-layout", version = "0.1.0" }
zng-state-map = { path = "../zng-state-map", version = "0.1.0" }
zng-view-api = { path = "../zng-view-api", version = "0.1.0" }
zng-task = { path = "../zng-task", version = "0.1.0" }
zng-ext-image = { path = "../zng-ext-image", version = "0.1.0" }
zng-color = { path = "../zng-color", version = "0.1.0" }

serde = { version = "1", features = ["derive"] }
bitflags = "2"
atomic = "0.6"
tracing = "0.1"
parking_lot = "0.12"
