[package]
name = "zero-ui-macros"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2018"

[dependencies]
# local
zero-ui-proc-macros = { path = "../zero-ui-proc-macros" }