[package]
name = "zng-wgt-wrap"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-ext-font ={ path = "../zng-ext-font" }
zng-layout = { path = "../zng-layout" }
zng-app = { path = "../zng-app" }

tracing = "0.1"