[package]
name = "zng-wgt-wrap"
version = "0.2.0"
authors = ["The Zng Project Developers"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"
description = "Part of the zng project."
documentation = "https://docs.rs/zng-wgt-wrap"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-wgt = { path = "../zng-wgt", version = "0.2.0" }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.2.0" }
zng-ext-font = { path = "../zng-ext-font", version = "0.2.0" }
zng-layout = { path = "../zng-layout", version = "0.2.0" }
zng-app = { path = "../zng-app", version = "0.2.0" }

tracing = "0.1"
