[package]
name = "zero-ui-wgt-text_input"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }
zero-ui-wgt-fill = { path = "../zero-ui-wgt-fill" }
zero-ui-wgt-filter = { path = "../zero-ui-wgt-filter" }
zero-ui-wgt-layer = { path = "../zero-ui-wgt-layer" }
zero-ui-wgt-style = { path = "../zero-ui-wgt-style" }
zero-ui-wgt-undo = { path = "../zero-ui-wgt-undo" }
zero-ui-wgt-size_offset = { path = "../zero-ui-wgt-size_offset" }
zero-ui-wgt-view = { path = "../zero-ui-wgt-view" }
zero-ui-wgt-input = { path = "../zero-ui-wgt-input" }
zero-ui-wgt-menu = { path = "../zero-ui-wgt-menu" }
zero-ui-wgt-rule_line = { path = "../zero-ui-wgt-rule_line" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-data = { path = "../zero-ui-wgt-data" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-ext-input = { path = "../zero-ui-ext-input" }
zero-ui-ext-clipboard = { path = "../zero-ui-ext-clipboard" }
