[package]
name = "zero-ui-wgt"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["debug_default"]

# Signal the build script to enable the `dyn_*`, `inspector` and `trace_widget` features for debug builds.
#
# Enabled by default.
debug_default = ["zero-ui-var/debug_default"]

# Box closures at opportune places, such as `Var::map`, reducing the number of monomorphised types.
#
# This speeds-up compilation time at the cost of runtime.
dyn_closure = ["zero-ui-var/dyn_closure"]

[dependencies]
zero-ui-clone_move = { path = "../zero-ui-clone_move" }
zero-ui-app = { path = "../zero-ui-app" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-state_map = { path = "../zero-ui-state_map" }
zero-ui-layout = { path = "../zero-ui-layout" }

paste = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "zero-ui-wgt/doc/html-in-header.html"]
