[package]
name = "zero-ui-wgt-view"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zero-ui-app/README.md"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-var = { path = "../zero-ui-var" }
zero-ui-wgt-container = { path = "../zero-ui-wgt-container" }

parking_lot = "0.12"
tracing = "0.1"

[dev-dependencies]
zero-ui-app = { path = "../zero-ui-app" }