[package]
name = "zero-ui-wgt-link"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zero-ui-app/README.md"

[dependencies]
zero-ui-wgt = { path = "../zero-ui-wgt" }
zero-ui-wgt-style = { path = "../zero-ui-wgt-style" }
zero-ui-wgt-access = { path = "../zero-ui-wgt-access" }
zero-ui-wgt-text = { path = "../zero-ui-wgt-text" }
zero-ui-wgt-input = { path = "../zero-ui-wgt-input" }
zero-ui-wgt-filter = { path = "../zero-ui-wgt-filter" }