name: CI

on:
  pull_request:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - 'docs/**'
      - 'TODO/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo do prebuild
      - run: cargo clean
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilt
          path: zng-view-prebuilt/lib/libzng_view.so
  check:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt
          path: zng-view-prebuilt/lib
      - uses: Swatinem/rust-cache@v2
      - run: cargo do version --verbose
      - run: cargo do fmt --check
      - run: cargo do check
  doc:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt
          path: zng-view-prebuilt/lib
      - uses: Swatinem/rust-cache@v2
      - run: cargo do doc
      - run: cargo clean
  test:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: prebuilt
        path: zng-view-prebuilt/lib
    - uses: Swatinem/rust-cache@v2
    - run: cargo do test --lib --bins --tests
    - run: cargo clean
  test-doc:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt
          path: zng-view-prebuilt/lib
      - uses: Swatinem/rust-cache@v2
      - run: cargo do test --doc
      - run: cargo clean
  test-macro:
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prebuilt
          path: zng-view-prebuilt/lib
      - uses: Swatinem/rust-cache@v2
      - run: cargo do test --macro --all
      - run: cargo clean
  test-all:
    runs-on: ubuntu-latest
    needs: [check, doc, test, test-doc, test-macro]
    steps:
      - run: exit 0
  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs: [test-all]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: prebuilt
          failOnError: false

