name: CI

on:
  pull_request:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - 'docs/**'
      - 'TODO/**'

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo do version --verbose 
    - run: cargo fmt -- --check
    - run: cargo do prebuild
    - run: cargo clean
    - run: cargo do check
    - run: cargo clean
    - run: cargo do doc
    - run: cargo clean
    - run: cargo do test
    - run: cargo clean
