name: CI

on:
  pull_request:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - 'docs/**'
      - 'TODO/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'

jobs:
  check:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - run: cargo do version --verbose
      - run: cargo fmt -- --check
      - run: cargo do check
  doc:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - run: cargo do doc
      - run: cargo clean
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo do prebuild
    - run: cargo clean
    - run: cargo do test
    - run: cargo clean
