name: Release -> Test -> Tag

on:
  push:
    branches: [ "release" ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Fmt Check
          run: cargo fmt -- --check
        - name: Prebuild
          run: |
            cargo do prebuild
            cargo clean
        - name: Check
          run: |
            cargo do check
            cargo clean
        - name: Test
          run: cargo do test
    
  tag:
    name: tag
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cargo do publish_version_tag --execute
