name: Release -> Test -> Tag

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  test-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
        - if: matrix.os == 'windows-latest'
          name: Install LLVM CC
          uses: KyleMayes/install-llvm-action@v2
          with:
            version: "16"
            env: true
        - uses: actions/checkout@v4
          with:
            ref: release
        - name: Fmt Check
          run: cargo fmt -- --check
        - name: Prebuild
          run: |
            cargo do prebuild
            cargo clean
        - name: Check
          run: |
            cargo do check
            cargo clean
        - name: Test
          run: cargo do test
  
  test-cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Test Cargo Publish
        run: cargo do publish --test

  tag:
    name: tag
    runs-on: ubuntu-latest
    needs: [test-release, test-cargo-publish]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release
      - run: cargo do publish_version_tag --execute
