name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: 'zng-view-prebuilt/lib/libzng_view.so'
          - os: windows-latest
            file: 'zng-view-prebuilt/lib/zng_view.dll'
          - os: macos-latest
            file: 'zng-view-prebuilt/lib/libzng_view.dylib'

    name: prebuild (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Fmt Check
          run: cargo fmt -- --check
        - name: Prebuild
          run: |
            cargo do prebuild
            cargo clean
        - name: Check
          run: |
            cargo do check
            cargo clean
        - name: Test
          run: cargo do test
        - name: Upload artifacts
          uses: actions/upload-artifact@v1
          with:
            name: prebuilt-${{ matrix.os }}
            path: ${{ matrix.file }}
    
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: prebuilt-ubuntu-latest
          path: prebuilt
      - uses: actions/download-artifact@v1
        with:
          name: prebuilt-windows-latest
          path: prebuilt
      - uses: actions/download-artifact@v1
        with:
          name: prebuilt-macos-latest
          path: prebuilt
      - run: ls --all ./prebuilt
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "prebuilt/*"