name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prebuild
      run: cargo do prebuild
    - name: Build
      run: cargo do build
    - name: Run tests
      run: cargo do test
