name: Find Breaking Changes

on:
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - name: install cargo-semver-checks
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-semver-checks
      - run: cargo do semver_check