name: Find Breaking Changes

on:
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: install cargo-about
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-about
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          shared-key: zng-semver-checks