[package]
name = "zng-state_map"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"


[dependencies]
zng-unique_id = { path = "../zng-unique_id" }

bytemuck = { version = "1" }
pretty-type-name = "1"