[package]
name = "zng-wgt-text-input"
version = "0.1.0"
authors = ["Samuel Guerra <sam.rodr.g@gmail.com>", "Well <well-r@hotmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../zng-app/README.md"

[dependencies]
zng-wgt = { path = "../zng-wgt" }
zng-wgt-text = { path = "../zng-wgt-text" }
zng-wgt-container = { path = "../zng-wgt-container" }
zng-wgt-fill = { path = "../zng-wgt-fill" }
zng-wgt-filter = { path = "../zng-wgt-filter" }
zng-wgt-layer = { path = "../zng-wgt-layer" }
zng-wgt-style = { path = "../zng-wgt-style" }
zng-wgt-undo = { path = "../zng-wgt-undo" }
zng-wgt-size-offset = { path = "../zng-wgt-size-offset" }
zng-wgt-input = { path = "../zng-wgt-input" }
zng-wgt-button = { path = "../zng-wgt-button" }
zng-wgt-menu = { path = "../zng-wgt-menu" }
zng-wgt-rule-line = { path = "../zng-wgt-rule-line" }
zng-wgt-access = { path = "../zng-wgt-access" }
zng-wgt-data = { path = "../zng-wgt-data" }
zng-app = { path = "../zng-app" }
zng-ext-input = { path = "../zng-ext-input" }
zng-ext-clipboard = { path = "../zng-ext-clipboard" }
